name: .NET Core

on:
  push:  
    branches: [ beta, v1 ]

  pull_request:
    branches: [ beta, v1 ]

env:
  GITHUB: ${{ toJson(github) }}
  BUILD_VERSION: 0.0.${{ github.run_number }}
  
jobs:
   build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3
    
    - name: Build Project
      run: dotnet build /p:Version=$BUILD_VERSION-${GITHUB_REF##*/} --configuration Release -o Output
    
    - name: Discord WebHook
      if: always()
      shell: pwsh
      run: |
        wget https://raw.githubusercontent.com/Yucked/Scripy/master/Powershell/ActionSend.ps1
        pwsh .\ActionSend.ps1 ${{ secrets.WEBHOOK }} ${{ job.status }}
